import axios from 'axios'
const BASE = import.meta.env.VITE_API_URL || ''
export const api = axios.create({ baseURL: `${BASE}/api/v1`, headers: { 'Content-Type': 'application/json' } })
api.interceptors.request.use(cfg => { const t = localStorage.getItem('access_token'); if (t) cfg.headers.Authorization = `Bearer ${t}`; return cfg })
api.interceptors.response.use(r => r, err => { if (err.response?.status === 401) { localStorage.removeItem('access_token'); window.location.href = '/login' } return Promise.reject(err) })
export const login = (e: string, p: string) => api.post('/auth/login', { email: e, password: p })
export const getStudies = (params?: Record<string,string>) => api.get('/studies/', { params })
export const getStudy = (id: string) => api.get(`/studies/${id}`)
export const createStudy = (data: Record<string,unknown>) => api.post('/studies/', data)
export const loadStudyFromConnector = (data: Record<string,unknown>) => api.post('/studies/load-from-connector', data)
export const updateStudy = (id: string, data: Record<string,unknown>, reason?: string) => api.patch(`/studies/${id}`, data, { params: reason ? { reason } : {} })
export const deleteStudy = (id: string, reason?: string) => api.delete(`/studies/${id}`, { params: reason ? { reason } : {} })
export const approveDataset = (id: string, comment: string) => api.post(`/reports/${id}/approve`, null, { params: { comment } })
export const getGroups = (sid: string) => api.get(`/studies/${sid}/groups`)
export const createGroup = (sid: string, d: Record<string,unknown>) => api.post(`/studies/${sid}/groups`, d)
export const getAnimals = (sid: string) => api.get(`/studies/${sid}/animals`)
export const uploadFile = (sid: string, file: File, hint = 'AUTO') => { const f = new FormData(); f.append('file', file); f.append('domain_hint', hint); return api.post(`/ingestion/${sid}/upload`, f, { headers: { 'Content-Type': 'multipart/form-data' } }) }
export const getTaskStatus = (tid: string) => api.get(`/ingestion/task/${tid}`)
export const getRawMeasurements = (sid: string, measurementType?: string) => api.get(`/ingestion/measurements/${sid}`, { params: measurementType ? { measurement_type: measurementType } : {} })
export const getRawMeasurementConfig = (sid: string) => api.get(`/ingestion/measurements/${sid}/config`)
export const importSampleCollections = (sid: string, file: File) => { const form = new FormData(); form.append('file', file); return api.post(`/ingestion/sample-collections/${sid}/import-csv`, form, { headers: { 'Content-Type': 'multipart/form-data' } }) }
export const importRawMeasurements = (sid: string, file: File, supplementalFile: File | null, measurementType: string, deleteDomainData: boolean, reasonForEdit: string, reasonForNew: string, reasonForDelete: string, rTransformXptCommandFile: string, rTransformXlsxCommandFile: string, relatedFiles: Record<string, string>) => {
  const form = new FormData(); form.append('file', file); if (supplementalFile) form.append('supp_file', supplementalFile); form.append('measurement_type', measurementType); form.append('delete_domain_data', String(deleteDomainData)); form.append('reason_for_edit', reasonForEdit); form.append('reason_for_new', reasonForNew); form.append('reason_for_delete', reasonForDelete); form.append('r_transform_xpt_command_file', rTransformXptCommandFile); form.append('r_transform_xlsx_command_file', rTransformXlsxCommandFile)
  Object.entries(relatedFiles).forEach(([key, value]) => form.append(key, value))
  return api.post(`/ingestion/measurements/${sid}/import-csv`, form, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const importRelrec = (sid: string, file: File) => {
  const form = new FormData(); form.append('file', file)
  return api.post(`/ingestion/relrec/${sid}/import-csv`, form, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const updateRawMeasurement = (sid: string, rowId: string, data: Record<string, string>) => api.put(`/ingestion/measurements/${sid}/${rowId}`, data)
export const deleteRawMeasurement = (sid: string, rowId: string) => api.delete(`/ingestion/measurements/${sid}/${rowId}`)
export const exportRawMeasurements = (sid: string, measurementType?: string) => api.get(`/ingestion/measurements/${sid}/export-csv`, { params: measurementType ? { measurement_type: measurementType } : {}, responseType: 'blob' })
export const getSendDomains = () => api.get('/transformation/domains')
export const runTransformation = (sid: string, codes: string[], fmt = 'XPT') => api.post(`/transformation/${sid}/run`, { domain_codes: codes, output_format: fmt })
export const getStudyDomains = (sid: string) => api.get(`/transformation/${sid}/domains`)
export const getPkShell = (sid: string, domain: 'PC'|'PP') => api.get(`/transformation/${sid}/pc-pp-shell/${domain}`, { responseType: 'blob' })
export const getCTVersions = () => api.get('/ct/versions')
export const getCTCodelists = (version?: string) => api.get('/ct/codelists', { params: version ? { version } : {} })
export const getCTCodelistTerms = (codelist: string, version?: string) => api.get(`/ct/codelists/${encodeURIComponent(codelist)}`, { params: version ? { version } : {} })
export const installBundledCT = () => api.post('/ct/install-bundled')
export const installCdiscCT = (file: File, version: string, previousVersion: string) => {
  const form = new FormData()
  form.append('file', file)
  form.append('version', version)
  form.append('previous_version', previousVersion)
  return api.post('/ct/install-cdisc', form, { headers: { 'Content-Type': 'multipart/form-data' } })
}
export const exportCTCsv = (version?: string) => api.get('/ct/export-csv', { params: version ? { version } : {}, responseType: 'blob' })
export const removeCTVersion = (version: string) => api.delete(`/ct/versions/${encodeURIComponent(version)}`)
export const getCTMappings = (params?: Record<string,string>) => api.get('/ct/mappings', { params })
export const updateCTMapping = (id: string, data: Record<string,unknown>) => api.patch(`/ct/mappings/${id}`, data)
export const bulkMapCT = (domain: string, variable: string, sid?: string) => api.post('/ct/mappings/bulk-map', null, { params: { domain_code: domain, variable_name: variable, ...(sid ? { study_id: sid } : {}) } })
export const getDomainTemplate = (code: string) => api.get(`/output-mapping/templates/${code}`)
export const getOutputMappings = (sid: string) => api.get(`/output-mapping/${sid}`)
export const getFocusMappings = (sid: string) => api.get(`/output-mapping/focus/${sid}`)
export const getFocusMappingOptions = (sid: string) => api.get(`/output-mapping/focus/${sid}/options`)
export const createFocusMapping = (sid: string, data: { domain_code: string; fixed_type: string; source_value: string; focid: string; category?: string; subcategory?: string; tissue_flag?: string; locator?: string }) => api.post(`/output-mapping/focus/${sid}`, data)
export const deleteFocusMapping = (sid: string, mappingId: string) => api.delete(`/output-mapping/focus/${sid}/${mappingId}`)
export const runValidation = (sid: string, codes: string[]) => api.post(`/validation/${sid}/run`, { domain_codes: codes })
export const getValidationResults = (sid: string) => api.get(`/validation/${sid}/results`)
export const generatePackage = (sid: string, fmt = 'XPT', defineVersion = '2.1') => api.post(`/reports/${sid}/package`, { include_define_xml: true, include_sdrg: true, include_xpt: true, output_format: fmt, define_version: defineVersion })
export const getAuditTrail = (sid: string) => api.get(`/reports/${sid}/audit-trail`)

// FS5 — Updated login with username (not email)
export const loginWithCredentials = (username: string, password: string, language: string, dateFormat: string) =>
  api.post('/auth/login', { username, password, language, date_format: dateFormat })
export const getUserPreferences = (username: string) => api.get(`/auth/preferences/${username}`)
