# Savante base-table keys used to resolve Pristima supplemental records.
SEND_BW=SEDDM_ID,BWTESTCD,BWDTC,BWUSCHFL
SEND_CL=SEDDM_ID,CLTESTCD,CLCAT,CLTPT,CLDTC,CLSTRESC,CLSTAT
SEND_DD_EXTRA=SEDDS_ID,TIS_NAME,DDORRES
SEND_DM=SEDDM_ID
SEND_DS=SEDDM_ID
SEND_EG=SEDDM_ID,EGTESTCD,EGDTC,EGTPT
SEND_EX=SEDDM_ID,EXTRT,EXSTDTC
SEND_FW=SEDDM_ID,CAGE_NUMBER,FWTESTCD,FWDTC,FWENDTC
SEND_LB=SEDDM_ID,LBTESTCD,LBSPEC,LBDTC,LBTPT
SEND_MI.MA=SEDDM_ID,SEDTIS_ID,MIORRES,MISTAT
SEND_MI.MI=SEDDM_ID,SEDTIS_ID,MIORRES,MASTAT
SEND_PM=SEDDM_ID,PMORRES,PMDTC,PMTPT
SEND_OM=SEDDM_ID,OMTESTCD,SEDTIS_ID
SEND_SC=SEDDM_ID,SCTESTCD,SCDTC
SEND_FM=SEDDM_ID,FETUSID,ICORRES
SEND_PY=SEDDM_ID,FETUSID,FMTESTCD
SEND_MI.FX=SEDDM_ID,PYTESTCD,PYRESLOC
SEND_DP=SEDDM_ID
